test:
	 g++ lr_unit_test.cpp ./../../linear_regression/linear_regression_nd/lr.cpp -o lr_unit_test
	 ./lr_unit_test
test-debug:
	 g++  -g lr_unit_test.cpp ./../../linear_regression/linear_regression_nd/lr.cpp -o lr_unit_test
clean:
	 rm ./lr_unit_test

