test:
	 g++ ./driver.cpp ./../linear_regression_nd/lr.cpp ./../../utils/csv_helper.cpp -o lr_run
test-debug:
	 g++ -g ./driver.cpp ./../linear_regression_nd/lr.cpp ./../../utils/csv_helper.cpp -o lr_run
clean:
	 rm ./lr_run
